# FROM 533267334695.dkr.ecr.ap-south-1.amazonaws.com/python3:slim-3.6
FROM python:3.6-slim
# FROM 654654515013.dkr.ecr.ap-south-1.amazonaws.com/python_3_7_slim:latest
WORKDIR /app
COPY . /app
RUN pip3 install -r requirements.txt
EXPOSE 5000
CMD ["python3","app-modified.py"]
