apiVersion: apps/v1
kind: Deployment
metadata:
  name: forntend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend #this should be matched with the container labels
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${FRONTEND_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - name: frontend-port
          containerPort: 5000
        env:
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: endgame-secret
              key: backend_url
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 100Mi
            cpu: 100m
